openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the documentation for Water Tracker API. Water Tracker is a web application that helps users monitor their daily water intake, set personal goals, and review statistics. The main goal of the application is to improve users' water balance by providing a convenient tool for tracking and analyzing their habits.
tags:
  - name: Authentication
    description: Authorization endpoints
  - name: Users
    description: Endpoints for changing user information.
  - name: Water
    description: Endpoints for water quantity managment and statistics.
servers:
  - url: http://localhost:3000
  - url: https://watertracker-app-if0o.onrender.com/api
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/registerPost.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/loginPost.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refreshPost.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logoutPost.yaml'
   /user:
    get:
      $ref: '../swagger/paths/user/userGet.yaml'
    patch:
      $ref: '../swagger/paths/user/userPatch.yaml'
  /user/avatar:
    patch:
      $ref: '../swagger/paths/user/userAvatarPatch.yaml'
  /water:
    post:
       $ref: '../swagger/paths/water/post.yaml'
  /water/water-rate:
    patch:
      $ref: '../swagger/paths/water/patch.yaml'
  /water/today:
    get:
      $ref: '../swagger/paths/water/get.yaml'
  /water/month:
    get:
      $ref: '../swagger/paths/water/month/get.yaml'
  /water/{waterId}:
    patch:
      $ref: '../swagger/paths/water/{waterId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{waterId}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
